# Generated by Django 5.0.7 on 2024-07-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='therapist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
